export function repairPrivateUseMathGlyphs(value) {
  let text = String(value || "");

  text = text
    .replace(/\uF060\s*([A-Za-z]+)/g, "\\bar{$1}")
    .replace(/([A-Za-z])\uF024/g, "\\hat{$1}")
    .replace(/\uF04C(?=\s+(?:log|\\log)\b)/g, "\\ldots");

  return text.replace(/[\uE000-\uF8FF]/g, (char) =>
    PRIVATE_USE_MATH_GLYPHS.has(char) ? PRIVATE_USE_MATH_GLYPHS.get(char) : char);
}

export const PRIVATE_USE_MATH_GLYPHS = new Map(Object.entries({
  "\uF020": " ",
  "\uF022": "∀",
  "\uF024": "\u0302",
  "\uF028": "(",
  "\uF029": ")",
  "\uF02B": "+",
  "\uF02D": "-",
  "\uF03C": "<",
  "\uF03D": "=",
  "\uF03E": ">",
  "\uF044": "Δ",
  "\uF04C": "\\Lambda",
  "\uF05B": "[",
  "\uF05D": "]",
  "\uF05E": "⊥",
  "\uF060": "¯",
  "\uF061": "α",
  "\uF062": "β",
  "\uF064": "δ",
  "\uF066": "ϕ",
  "\uF067": "γ",
  "\uF06C": "λ",
  "\uF06D": "μ",
  "\uF070": "π",
  "\uF071": "θ",
  "\uF07B": "{",
  "\uF07D": "}",
  "\uF077": "ω",
  "\uF0A2": "″",
  "\uF0A3": "≤",
  "\uF0A5": "∞",
  "\uF0AE": "→",
  "\uF0B0": "°",
  "\uF0B1": "±",
  "\uF0B3": "≥",
  "\uF0B4": "×",
  "\uF0B9": "≠",
  "\uF0BC": "…",
  "\uF0BD": "|",
  "\uF0C7": "∩",
  "\uF0C8": "∪",
  "\uF0CC": "⊂",
  "\uF0CE": "∈",
  "\uF0D0": "∠",
  "\uF0D7": "⋅",
  "\uF0DB": "⇔",
  "\uF0E0": "∅",
  "\uF0E5": "∑",
  "\uF0E6": "(",
  "\uF0E7": "",
  "\uF0E8": ")",
  "\uF0E9": "[",
  "\uF0EA": "",
  "\uF0EB": "]",
  "\uF0EC": "{",
  "\uF0ED": "{",
  "\uF0EE": "{",
  "\uF0EF": "|",
  "\uF0F2": "∫",
  "\uF0F6": "(",
  "\uF0F7": "",
  "\uF0F8": ")",
  "\uF0F9": "]",
  "\uF0FA": "",
  "\uF0FB": "]",
  "\uF0FC": "}",
  "\uF0FD": "}",
  "\uF0FE": "}",
}));
