import { useEffect, useState } from "react";
import { usePartnerAuth } from "@/hooks/usePartnerAuth";
import { partnerApi } from "@/lib/partnerApi";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { Loader2, Percent, Wallet, CheckCircle, Clock } from "lucide-react";

function fmt(n: number) {
  return `₹${Number(n).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
}

export default function PartnerCommission() {
  const { token } = usePartnerAuth();
  const [stats, setStats] = useState<any>(null);
  const [payouts, setPayouts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!token) return;
    Promise.all([partnerApi.stats(token), partnerApi.payouts(token)]).then(([s, p]) => {
      setStats(s);
      setPayouts(p.payouts || []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [token]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (!stats) {
    return (
      <div className="flex items-center justify-center h-64 text-muted-foreground text-sm">
        Failed to load commission data. Please refresh.
      </div>
    );
  }

  const summaryCards = [
    {
      label: "Commission Rate",
      value: `${stats.currentSlabRate}%`,
      icon: Percent,
      color: "text-primary",
      bg: "bg-primary/10",
    },
    {
      label: "Total Earned",
      value: fmt(stats.paidCommission + stats.pendingCommission),
      icon: Wallet,
      color: "text-blue-600",
      bg: "bg-blue-100",
    },
    {
      label: "Paid Out",
      value: fmt(stats.paidCommission),
      icon: CheckCircle,
      color: "text-green-600",
      bg: "bg-green-100",
    },
    {
      label: "Pending",
      value: fmt(stats.pendingCommission),
      icon: Clock,
      color: "text-orange-600",
      bg: "bg-orange-100",
    },
  ];

  return (
    <div className="p-8 space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Commission</h1>
        <p className="text-muted-foreground mt-1">Your earnings and payout history</p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {summaryCards.map(({ label, value, icon: Icon, color, bg }) => (
          <Card key={label} className="shadow-sm">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-xs font-medium text-muted-foreground">{label}</CardTitle>
              <div className={`w-8 h-8 rounded-full ${bg} flex items-center justify-center`}>
                <Icon className={`w-4 h-4 ${color}`} />
              </div>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-foreground">{value}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Commission explanation */}
      <Card className="shadow-sm bg-primary/5 border-primary/20">
        <CardContent className="pt-5">
          <p className="text-sm text-foreground">
            <strong>How commission works:</strong> You earn {stats.currentSlabRate}% of the revenue
            generated by students who signed up using your referral code. Payouts are processed monthly
            by the Merit Launchers marketing team.
          </p>
        </CardContent>
      </Card>

      {/* Payout History */}
      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle>Payout History</CardTitle>
        </CardHeader>
        <CardContent className="p-0 overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Month</TableHead>
                <TableHead className="text-right">Revenue</TableHead>
                <TableHead className="text-right">Rate</TableHead>
                <TableHead className="text-right">Commission</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Paid</TableHead>
                <TableHead>Paid Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {payouts.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-12 text-muted-foreground">
                    No payout records yet
                  </TableCell>
                </TableRow>
              ) : payouts.map((p) => (
                <TableRow key={p.id}>
                  <TableCell className="font-medium">{p.month}</TableCell>
                  <TableCell className="text-right">{fmt(p.gross_revenue)}</TableCell>
                  <TableCell className="text-right">{p.weighted_commission_rate}%</TableCell>
                  <TableCell className="text-right font-semibold">{fmt(p.commission_amount)}</TableCell>
                  <TableCell>
                    {p.status === "paid" ? (
                      <Badge className="bg-green-100 text-green-800 border-0">Paid</Badge>
                    ) : (
                      <Badge className="bg-yellow-100 text-yellow-800 border-0">Pending</Badge>
                    )}
                  </TableCell>
                  <TableCell className="text-right">
                    {p.paid_amount ? fmt(p.paid_amount) : "—"}
                  </TableCell>
                  <TableCell className="text-sm text-muted-foreground">
                    {p.paid_at ? new Date(p.paid_at).toLocaleDateString("en-IN") : "—"}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
